# Generated by Django 5.0.3 on 2024-03-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sucursal',
            new_name='Sucursale',
        ),
        migrations.AlterField(
            model_name='instrumento',
            name='precio',
            field=models.IntegerField(max_length=7),
        ),
    ]
